-- SUMAS School Fees Payment Tracking and Receipt System
-- Database schema (SQLite)
--
-- Redesigned around an Invoice -> external payment -> automatic-match
-- workflow (modeled on the University of Nigeria, Nsukka's Remita-based
-- system), replacing the earlier "submit a claim, admin verifies it by
-- eye" workflow. See PROJECT_BRIEF.md for the full rationale.
--
-- Tables: student, administrator, fee_category, invoice, receipt,
-- unmatched_payment, department_program

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS student (
    student_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    reg_number       TEXT NOT NULL UNIQUE,
    full_name        TEXT NOT NULL,
    department       TEXT NOT NULL,
    faculty          TEXT NOT NULL,
    level            TEXT NOT NULL,
    password_hash    TEXT NOT NULL,
    date_registered  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- How far a department's own programme actually runs — most run to 400
-- Level, but some (Nursing Science, for instance) run longer. Keyed by
-- department name (matching student.department/fee_category.department's
-- loose free-text convention — no separate `department` table exists
-- elsewhere in this schema either) rather than a foreign key, since a
-- department can exist here before or after any student/fee_category row
-- mentions it by name. A department with no row here defaults to 400 in
-- code (see `_max_level_for()` in app/student.py) — this table only needs
-- an entry for a department whose programme is NOT the common 400L case.
CREATE TABLE IF NOT EXISTS department_program (
    department  TEXT PRIMARY KEY,
    max_level   TEXT NOT NULL   -- e.g. '500' — the highest level students in this department reach
);

CREATE TABLE IF NOT EXISTS administrator (
    admin_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    staff_id         TEXT NOT NULL UNIQUE,
    full_name        TEXT NOT NULL,
    password_hash    TEXT NOT NULL
);

-- `level` is nullable on purpose: NULL means "applies to every level" (e.g.
-- a Departmental Fee that doesn't vary by level), while a specific value
-- ('100'..'400', matching student.level's free-text values) scopes that row
-- to just that level — e.g. School Fees, which commonly differs by level.
-- Any of the three category types may use either a specific level or NULL.
CREATE TABLE IF NOT EXISTS fee_category (
    fee_category_id  INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name    TEXT NOT NULL,           -- 'School Fees' | 'Departmental Fee' | 'Faculty Fee'
    session           TEXT NOT NULL,           -- e.g. '2025/2026'
    level             TEXT,                    -- e.g. '100'; NULL = applies to every level
    department        TEXT,                    -- populated only for Departmental Fee
    faculty           TEXT,                    -- populated only for Faculty Fee
    amount            DECIMAL(10,2) NOT NULL,
    UNIQUE (category_name, session, level, department, faculty)
);

-- An Invoice is generated by the student for one fee category and one
-- payment plan, and carries a unique payment_reference (modeled on
-- Remita's RRR) that the student pays externally against that reference.
-- Status starts 'Awaiting Payment' and becomes 'Paid' the instant
-- handle_payment_notification() (app/payments.py) matches an incoming
-- payment notification to it — no admin action in the normal path.
CREATE TABLE IF NOT EXISTS invoice (
    invoice_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id        INTEGER NOT NULL REFERENCES student(student_id),
    fee_category_id   INTEGER NOT NULL REFERENCES fee_category(fee_category_id),
    payment_plan      TEXT NOT NULL,           -- 'Full Payment' | 'First Installment' | 'Second Installment'
    amount            DECIMAL(10,2) NOT NULL,
    payment_reference TEXT NOT NULL UNIQUE,
    status            TEXT NOT NULL DEFAULT 'Awaiting Payment', -- 'Awaiting Payment' | 'Paid'
    date_generated    TEXT NOT NULL DEFAULT (datetime('now')),
    date_paid         TEXT
);

-- Generated automatically the instant an invoice is marked Paid (never
-- created any other way). amount_in_words and the student's/school's
-- details are computed by JOIN at render time rather than stored here —
-- the same "never store what can be recomputed" principle already used
-- for a student's outstanding balance, so a receipt can never go stale
-- relative to the invoice or student record it describes.
CREATE TABLE IF NOT EXISTS receipt (
    receipt_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    invoice_id        INTEGER NOT NULL UNIQUE REFERENCES invoice(invoice_id),
    receipt_number    TEXT NOT NULL UNIQUE,
    date_issued       TEXT NOT NULL DEFAULT (datetime('now'))
);

-- The admin exception queue: a payment notification (real gateway or the
-- simulator) whose reference did not match any invoice, or whose amount
-- didn't match the invoice it did reference. An admin resolves a row
-- either by matching it to the correct invoice (which runs it back
-- through handle_payment_notification with a corrected reference) or by
-- dismissing it. This is the ONLY place a human is expected to act on a
-- payment under normal operation.
CREATE TABLE IF NOT EXISTS unmatched_payment (
    unmatched_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    reference_received  TEXT NOT NULL,
    amount_received     DECIMAL(10,2) NOT NULL,
    date_received        TEXT NOT NULL DEFAULT (datetime('now')),
    resolved            INTEGER NOT NULL DEFAULT 0,  -- SQLite has no BOOLEAN; 0/1
    resolved_by          INTEGER REFERENCES administrator(admin_id),
    date_resolved        TEXT
);

CREATE INDEX IF NOT EXISTS idx_student_dept_level ON student(department, level);
CREATE INDEX IF NOT EXISTS idx_invoice_student ON invoice(student_id);
CREATE INDEX IF NOT EXISTS idx_invoice_status ON invoice(status);
CREATE INDEX IF NOT EXISTS idx_unmatched_resolved ON unmatched_payment(resolved);
